module HTTPX
  def self.plugin: (*untyped plugins, **untyped keywords) -> untyped
  def self.with: (?untyped options, **untyped keywords) -> untyped
  def self.get: (String url, ?params: Hash[untyped, untyped] params, **untyped keywords) -> untyped
  def self.post: (String url, ?json: untyped json, ?form: untyped form, ?body: untyped body, ?params: Hash[untyped, untyped] params, **untyped keywords) -> untyped
  def self.head: (String url, **untyped keywords) -> untyped
end


module OpenSSL
  module SSL
    VERIFY_NONE: untyped
  end
end

module Rack
  module Mime
    MIME_TYPES: Hash[String, String]
  end
end

module RSS
  module Parser
    def self.parse: (String source, bool validate) -> untyped
  end
end

module R3x
  module Concerns
    module Logger
      def logger: () -> untyped
    end
  end

  module Policy
    def self.dry_run_for: (Symbol key, ?untyped dry_run) -> bool
  end

  module Env
    def self.fetch: (String name) -> String?
    def self.fetch!: (String name) -> String
    def self.fetch_boolean: (String name) -> bool?
    def self.present?: (String name) -> bool
    def self.secure_fetch: (String name, prefix: String | Regexp prefix) -> String
  end

  module Client
    module GoogleAuth
      def self.require_gmail!: () -> void
      def self.require_sheets!: () -> void
      def self.from_env: (project: String project, scope: String scope) -> untyped
      def self.resolve_scope: (String alias_name) -> String
    end
  end

  module GemLoader
    def self.require: (String feature) -> bool
  end
end


class Tempfile
  def self.new: (Array[String?] basename) -> Tempfile

  def binmode: () -> Tempfile

  def write: (untyped content) -> Integer

  def rewind: () -> Integer

  def close: () -> nil

  def unlink: () -> nil
end

module URI
  def self.parse: (String uri) -> untyped
end

module Marcel
  module MimeType
    def self.for: (untyped io) -> String?
  end
end

module MultiJSON
  def self.parse: (String string, ?untyped options) -> untyped
  def self.generate: (untyped object, ?untyped options) -> String
end

module Google
  module Apis
    module GmailV1
      class Message
        def initialize: (?raw: String raw) -> void
      end

      class GmailService
        def authorization=: (untyped authorization) -> untyped
      end
    end

    module SheetsV4
      class SheetsService
        def authorization=: (untyped authorization) -> untyped
        def get_spreadsheet_values: (String spreadsheet_id, String range) -> untyped
      end
    end
  end
end

module Mail
  def self.new: () -> untyped

  class Part
    def self.new: () { (Mail::Part) -> untyped } -> Mail::Part
    def body: () -> untyped
    def body=: (String? body) -> untyped
  end
end

module RubyLLM
  module Provider
    def self.providers: () -> Hash[Symbol, untyped]

    def self.register: (Symbol name, untyped provider) -> void
  end

  module Providers
    class OpenAI
    end
  end

  def self.context: () { (untyped config) -> untyped } -> untyped
end

module SecureRandom
  def self.uuid: () -> String
end

module Base64
  def self.strict_encode64: (String data) -> String
end

class String
  def blank?: () -> bool
end
