module HTTPX
  def self.plugin: (*untyped plugins, **untyped keywords) -> untyped
  def self.with: (?untyped options, **untyped keywords) -> untyped
end


module OpenSSL
  module SSL
    VERIFY_NONE: untyped
  end
end

module Rack
  module Mime
    MIME_TYPES: Hash[String, String]
  end
end

module RSS
  module Parser
    def self.parse: (String source, bool validate) -> untyped
  end
end

module R3x
  module Concerns
    module Logger
      def logger: () -> untyped
    end
  end

  module Policy
    def self.dry_run_for: (Symbol key, ?untyped dry_run) -> bool
  end

  module Env
    def self.secure_fetch: (String name, prefix: String | Regexp prefix) -> String
  end

  module GemLoader
    def self.require: (String feature) -> bool
  end
end


class Tempfile
  def self.new: (Array[String?] basename) -> Tempfile

  def binmode: () -> Tempfile

  def write: (untyped content) -> Integer

  def rewind: () -> Integer

  def close: () -> nil

  def unlink: () -> nil
end

module URI
  def self.parse: (String uri) -> untyped
end

module Marcel
  module MimeType
    def self.for: (untyped io) -> String?
  end
end

module MultiJSON
  def self.parse: (String string, ?untyped options) -> untyped
  def self.generate: (untyped object, ?untyped options) -> String
end
