# https://docs.rubocop.org/rubocop/configuration.html
# Omakase Ruby styling for Rails
inherit_gem:
  rubocop-rails-omakase: rubocop.yml
require:
  - ./.rubocop/cop/r3x/prefer_logger_concern.rb
  - ./.rubocop/cop/r3x/avoid_hash_tap.rb
  - ./.rubocop/cop/r3x/prefer_r3x_env.rb
  - ./.rubocop/cop/r3x/prefer_httpx_response_json.rb
  - ./.rubocop/cop/r3x/prefer_httpx_raise_for_status.rb
plugins:
  - rubocop-thread_safety
  - rubocop-minitest

AllCops:
  NewCops: enable
  Exclude:
    - docs/**/*
    - workflows/**/*

Rails/Output:
  Exclude:
    - db/**/*

# Overwrite or add rules to create your own house style
#
# # Use `[a, [b, c]]` not `[ a, [ b, c ] ]`
# Layout/SpaceInsideArrayLiteralBrackets:
#   Enabled: false

Layout/IndentationConsistency:
  Enabled: true
  EnforcedStyle: normal

Layout/AccessModifierIndentation:
  Enabled: true

Layout/EmptyLinesAroundAccessModifier:
  Enabled: true
  EnforcedStyle: around

Style/ItBlockParameter:
  Enabled: true
  EnforcedStyle: allow_single_line

Style/EmptyLiteral:
  Enabled: true

Style/BlockDelimiters:
  Enabled: true
  EnforcedStyle: line_count_based

Style/TrivialAccessors:
  Enabled: true

Layout/LineLength:
  Enabled: true
  Max: 140
  AutoCorrect: false
  Exclude:
    - "test/**/*"

Rails/TimeZone:
  Enabled: true
  EnforcedStyle: strict

R3x/PreferLoggerConcern:
  Enabled: true
  Include:
    - "app/lib/r3x/client/**/*"

R3x/PreferR3xEnv:
  Enabled: true
  Include:
    - "app/**/*.rb"
    - "lib/**/*.rb"

R3x/PreferHttpxResponseJson:
  Enabled: true
  Include:
    - "app/**/*.rb"
    - "lib/**/*.rb"

R3x/PreferHttpxRaiseForStatus:
  Enabled: true
  Include:
    - "app/**/*.rb"
    - "lib/**/*.rb"

R3x/AvoidHashTap:
  Enabled: true

Layout/HashAlignment:
  Enabled: true
  EnforcedHashRocketStyle: table

Layout/ArgumentAlignment:
  Enabled: true
  EnforcedStyle: with_fixed_indentation

Layout/ArrayAlignment:
  Enabled: true
  EnforcedStyle: with_fixed_indentation

Layout/FirstArgumentIndentation:
  Enabled: true
  EnforcedStyle: consistent

Layout/FirstArrayElementIndentation:
  Enabled: true
  EnforcedStyle: consistent

Layout/FirstHashElementIndentation:
  Enabled: true
  EnforcedStyle: consistent

Layout/MultilineArrayBraceLayout:
  Enabled: true
  EnforcedStyle: symmetrical

Layout/MultilineHashBraceLayout:
  Enabled: true
  EnforcedStyle: symmetrical

Layout/MultilineMethodCallBraceLayout:
  Enabled: true
  EnforcedStyle: symmetrical

Layout/MultilineMethodDefinitionBraceLayout:
  Enabled: true
  EnforcedStyle: symmetrical

Minitest/MultipleAssertions:
  Enabled: false
