# https://docs.rubocop.org/rubocop/configuration.html
# Omakase Ruby styling for Rails
inherit_gem: {rubocop-rails-omakase: rubocop.yml}
plugins:
  - rubocop-thread_safety
  - rubocop-rubyfmt

AllCops:
  Exclude:
    - docs/**/*
    - workflows/**/*

Rails/Output:
  Exclude:
    - db/**/*

# Overwrite or add rules to create your own house style
#
# # Use `[a, [b, c]]` not `[ a, [ b, c ] ]`
# Layout/SpaceInsideArrayLiteralBrackets:
#   Enabled: false

Layout/IndentationConsistency:
  Enabled: true
  EnforcedStyle: normal

Layout/AccessModifierIndentation:
  Enabled: true

Layout/EmptyLinesAroundAccessModifier:
  Enabled: true
  EnforcedStyle: around

Style/ItBlockParameter:
  Enabled: true
  EnforcedStyle: allow_single_line

Layout/RedundantLineBreak:
  Enabled: true
  InspectBlocks: true
  Exclude:
    - 'test/**/*'

Style/BlockDelimiters:
  Enabled: true
  Exclude:
    - 'test/**/*'

Layout/LineLength:
  Enabled: true
  Max: 140
  AutoCorrect: false
  Exclude:
    - 'test/**/*'
