version: "1.0"
defaults:
  base_dir: ".."

hooks:
  post_create:
    - type: copy
      from: ".env"
      to: ".env"

    - type: copy
      from: "workflows/"
      to: "workflows/"

    - type: command
      command: mise trust

    - type: command
      command: bundle install && bundle exec rails db:prepare
