[settings]
idiomatic_version_file_enable_tools = ["ruby"]

[tools]
"gem:ruby-lsp" = "latest"
"gem:bundler-leak" = "0.3.0"
"gem:libyear-bundler" = "0.9.3"
"gem:next_rails" = "1.6.0"
"gem:rails_stats" = "2.2.0"
"gem:rubycritic" = "5.0.0"
"gem:skunk" = "0.5.4"
"github:AlDanial/cloc" = { version = "2.10", asset_pattern = "cloc-2.10.pl", bin = "cloc" }
dprint = "latest"
trivy = "0.73.0"

[env]
RAILS_ENV = "development"
