module R3x
  module Client
    class GoogleSheets
      def initialize: (spreadsheet_id: String spreadsheet_id, project: String project) -> void

      def read_rows: (range: String range, ?headers: bool headers) -> Array[untyped]

      private

      attr_reader spreadsheet_id: String
      attr_reader project: String
      attr_reader service: untyped

      def build_service: () -> untyped

      def make_unique_headers: (untyped headers) -> untyped

      def row_to_hash: (untyped headers, untyped row) -> Hash[untyped, untyped]
    end
  end
end
