module R3x
  module Client
    class HealthchecksIO
      include R3x::Concerns::Logger

      def initialize: (String check_uuid, ?ping_endpoint: String? ping_endpoint, ?ping_endpoint_env: String ping_endpoint_env) -> void

      def run: () { (HealthchecksIO, String) -> untyped } -> untyped

      def ping: (?body: String? body, ?rid: String? rid) -> HealthchecksIO::Response

      def fail: (?body: String? body, ?rid: String? rid) -> HealthchecksIO::Response

      def log: (lines: Array[String] | String lines, ?rid: String? rid) -> HealthchecksIO::Response

      def exit_status: (code: Integer code, ?body: String? body, ?rid: String? rid) -> HealthchecksIO::Response

      private

      attr_reader ping_url: String

      def connection: () -> untyped

      def send_start: (?rid: String? rid) -> HealthchecksIO::Response

      def make_request: (Symbol method, String path, ?body: String? body, ?rid: String? rid) -> HealthchecksIO::Response
    end
  end
end
