module R3x
  module Client
    class Markdownify
      include R3x::Concerns::Logger

      DEFAULT_METHOD: String

      def initialize: (url: String url, ?method: String method, ?retain_images: bool retain_images) -> void

      def convert: () -> Hash[String, untyped]

      private

      attr_reader url: String
      attr_reader method: String
      attr_reader retain_images: bool

      def dry_run_result: () -> Hash[String, untyped]

      def connection: () -> untyped
    end
  end
end
