module R3x
  module Workflow
    class DurableSet
      DEFAULT_TTL: untyped

      def initialize: (workflow_key: String workflow_key, ?name: Symbol | String name, ?ttl: untyped ttl) -> void

      def include?: (untyped member) -> bool

      def add: (untyped member, ?ttl: untyped ttl) -> untyped

      def add?: (untyped member, ?ttl: untyped ttl) -> untyped

      def delete: (untyped member) -> untyped
    end
  end
end
