module R3x
  module Workflow
    class Execution
      attr_reader workflow_key: String

      def initialize: (workflow_key: String workflow_key) -> void

      def previous_run_at: () -> untyped

      def first_run?: () -> bool
    end
  end
end
