default: &default
  dispatchers:
    - polling_interval: 1
      batch_size: 500
  workers:
    - queues: "*"
      threads: <%= ENV.fetch("JOB_THREADS", 3) %>
      processes: <%= ENV.fetch("JOB_CONCURRENCY", 1) %>
      polling_interval: 0.1
  scheduler:
    dynamic_tasks_enabled: true
    polling_interval: 5

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
