require "active_support/core_ext/integer/time"
require "r3x/log"
require "r3x/log/json_formatter"

Rails.application.configure do
  # Settings specified here will take precedence over those in config/application.rb.

  # Make code changes take effect immediately without server restart.
  config.enable_reloading = true

  # Do not eager load code on boot.
  config.eager_load = false

  # Use solid_cache for persistence across workflow runs
  config.cache_store = :solid_cache_store

  # Print deprecation notices to the Rails logger.
  config.active_support.deprecation = :log

  # Raise an error on page load if there are pending migrations.
  config.active_record.migration_error = :page_load

  # Highlight code that triggered database queries in logs.
  config.active_record.verbose_query_logs = true

  # Append comments with runtime information tags to SQL queries in logs.
  config.active_record.query_log_tags_enabled = true

  # Apply autocorrection by RuboCop to files generated by `bin/rails generate`.
  # config.generators.apply_rubocop_autocorrect_after_generate!

  config.active_job.queue_adapter = :solid_queue
  config.solid_queue.clear_finished_jobs_after = 2.weeks

  if R3x::Log.json?
    config.log_formatter = R3x::Log::JsonFormatter.new
  end

  config.solid_queue.logger = ActiveSupport::Logger.new(STDOUT).tap do |logger|
    logger.formatter = config.log_formatter if R3x::Log.json?
  end

  config.after_initialize do
    Rails.logger.info { "Log format: #{R3x::Log.format} (set R3X_LOG_FORMAT=json for structured output)" }
  end

  unless R3x::RuntimeProfile.headless?
    # Show full error reports.
    config.consider_all_requests_local = true

    # Enable server timing.
    config.server_timing = true

    # Enable/disable Action Controller caching. By default Action Controller caching is disabled.
    # Run rails dev:cache to toggle Action Controller caching.
    if Rails.root.join("tmp/caching-dev.txt").exist?
      config.public_file_server.headers = { "cache-control" => "public, max-age=#{2.days.to_i}" }
    else
      config.action_controller.perform_caching = false
    end

    # Highlight code that triggered redirect in logs.
    config.action_dispatch.verbose_redirect_logs = true

    # Raises error for missing translations.
    # config.i18n.raise_on_missing_translations = true

    # Annotate rendered view with file names.
    config.action_view.annotate_rendered_view_with_filenames = true

    # Raise error when a before_action's only/except options reference missing actions.
    config.action_controller.raise_on_missing_callback_actions = true

    # Disable Mission Control Jobs HTTP Basic auth in development
    config.mission_control.jobs.http_basic_auth_enabled = false
  end
end
