module R3x
  module Client
    class Llm
      module ProviderRegistry
        def self.register!: () -> void

        def self.register_opencode_go!: () -> void

        def self.opencode_go_provider_class: () -> singleton(Class)
      end
    end
  end
end
