module R3x
  module Client
    class Llm
      class ProviderConfiguration
        API_KEY_SUFFIX: String

        attr_reader api_key: String
        attr_reader config_api_key_attr: String

        def initialize: (api_key: String api_key, config_api_key_attr: String config_api_key_attr) -> void

        def self.resolve: (api_key_env: String api_key_env) -> ProviderConfiguration
      end
    end
  end
end
