module R3x
  module Client
    module Google
      class Gmail
        include R3x::Concerns::Logger

        def initialize: (project: String project) -> void

        def deliver: (to: String to, subject: String subject, body: String body, ?attachments: Array[Hash[Symbol, untyped]] attachments) -> Hash[String, String]

        private

        attr_reader project: String

        def build_service: () -> untyped

        def raw_message: (to: String to, subject: String subject, body: String body, attachments: Array[Hash[Symbol, untyped]] attachments) -> String
      end
    end
  end
end
