module R3x
  module Client
    module Google
      class Translate
        API_URL: String

        def initialize: (project: String project) -> void

        def translate: (untyped text, to: String to, ?from: String? from, ?format: String format) -> String

        private

        attr_reader project: String

        def authorization: () -> untyped

        def authorization_header: () -> Hash[String, String]

        def access_token: () -> String

        def request_body: (String text, to: String to, from: String? from, format: String format) -> Hash[Symbol, untyped]
      end
    end
  end
end
